import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "PokeDex",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link
        rel="shortcut icon"
        href="https://www.pokemon.com/static-assets/app/static3/img/og-default-image.jpeg"
        type="image/x-icon"
      />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
