name: Deploy React Book App from GitHub to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Still use ubuntu-latest for the job, but we will run Docker container below.

    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@v2

      - name: Build and Deploy in Amazon Linux
        uses: docker://amazonlinux:2  # Use the Amazon Linux 2 image
        with:
          args: |
            /bin/bash -c "
              yum install -y nodejs npm zip && \
              npm install && \
              npm run build && \
              zip -r BookAppFrontend.zip build/* && \
              echo 'Deployment package created.'
            "

      - name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Run string replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: "${{ secrets.ACCESS_KEY }}"
          aws_secret_key: "${{ secrets.SECRET_ACCESS_KEY }}"
          application_name: Hubsapp
          environment_name: HubsApp-env
          version_label: "app-${{ steps.format-time.outputs.replaced }}"
          region: ap-south-1
          deployment_package: BookAppFrontend.zip

      - name: Deployed!
        run: echo App deployed to ELB
